### ISSUE TITLE
AI Bot to Search for SAP Content: Request failed status code 500 - search-conversion

### ISSUE THREAD

**Issue by samuelaljackson** [afritzler/search-conversion#7]
Hey,
I get following error: Request failed with the status code 500.

What can I do?

**Comment by afritzler** [comment]
Is it possilbe to provide some log output?
```
cf logs APPNAME
```

**Comment by samuelaljackson** [comment]
At this time it is not possible to provide any log output:
`Retrieving logs for app .\search-conversion-master\ in org .... / space dev as .......`
There is no output anyway.

**Comment by afritzler** [comment]
That is weird. In case of a 500 error you CF application should dump an error. Did you modify the application manifest?

**Comment by samuelaljackson** [comment]
No, I did not modify the application manifest...

**Comment by afritzler** [comment]
On what CF instance did you deploy the service?

**Comment by samuelaljackson** [comment]
There should be an error log, but there is no output anyway...

**Comment by afritzler** [comment]
Do you get an `OK` back when you access the application URL?

**Comment by samuelaljackson** [comment]
@afritzler yes!

**Comment by samuelaljackson** [comment]
Yes!

**Comment by samuelaljackson** [comment]
On what CF instance did you deploy the service?

I do not know, I have to look up

**Comment by samuelaljackson** [comment]
I don't know, I have to look up! How can I find the instance?

**Comment by afritzler** [comment]
Are you by any chance working for SAP?

**Comment by afritzler** [comment]
And if so, can you please hit me up on slack?

**Comment by samuelaljackson** [comment]
I do not work für SAP

**Comment by samuelaljackson** [comment]
I do not work for SAP

**Comment by afritzler** [comment]
Are you in the CAI community slack channel?

**Comment by afritzler** [comment]
You can find me under the same name.

**Comment by samuelaljackson** [comment]
Thank you
