### ISSUE TITLE
go version depreciated

### ISSUE THREAD

**Issue by nithin19888** [afritzler/search-conversion#8]
Getting this error:

 Downloaded app package (2.1M)
   -----> Go Buildpack version 1.9.8
          **WARNING** [DEPRECATION WARNING]:
          **WARNING** Please use AppDynamics extension buildpack for Golang Application instrumentation
          **WARNING** for more details: https://docs.pivotal.io/partners/appdynamics/multibuildpack.html
   -----> Installing godep 80
          Copy [/tmp/buildpacks/65e58c60909bbd8fa93375867da12018/dependencies/52a892f00e80ca4fdcf27d9828c7aba1/godep-v80-linux-x64-cflinuxfs3-b60ac947.tgz]
   -----> Installing glide 0.13.3
          Copy [/tmp/buildpacks/65e58c60909bbd8fa93375867da12018/dependencies/f5e4affa54f8cf8e22cf524de5165a6e/glide-v0.13.3-linux-x64-cflinuxfs3-ef07acb5.tgz]
   -----> Installing dep 0.5.4
          Copy [/tmp/buildpacks/65e58c60909bbd8fa93375867da12018/dependencies/f1900fcb2de60a12ea6743ecf05e14d2/dep-v0.5.4-linux-x64-cflinuxfs3-79b3ab9e.tgz]
          ******ERROR** Unable to determine Go version to install: no match found for 1.11.x in [1.12.16 1.12.17 1.13.7 1.13.8 1.14]
   Failed to compile droplet: Failed to run all supply scripts: exit status 16
   Exit status 223****
   Cell 390b8e31-20b8-4a31-afab-faa384e46b9e stopping instance 49fe336e-8178-406d-9390-a5f55392d470
   Cell 390b8e31-20b8-4a31-afab-faa384e46b9e destroying container for instance 49fe336e-8178-406d-9390-a5f55392d470
Error staging application: App staging failed in the buildpack compile phase
FAILED

**Comment by afritzler** [comment]
Fixed with #9
